### ISSUE TITLE
compile Error

### ISSUE THREAD

**Issue by meagon** [jythontools/jython#51] opened 2016-11-16 15:23 UTC
```     
[java] warning(105): /dev/shm/full_build/work/checkout/jython/grammar/Python.g:1271:15: no lexer rule corresponding to token: INDENT
     [java] warning(105): /dev/shm/full_build/work/checkout/jython/grammar/Python.g:1278:10: no lexer rule corresponding to token: DEDENT
     [java] warning(200): /dev/shm/full_build/work/checkout/jython/grammar/Python.g:1986:59: Decision can match input such as "COMMA BACKQUOTE" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] warning(200): /dev/shm/full_build/work/checkout/jython/grammar/Python.g:1986:62: Decision can match input such as "COMMA" using multiple alternatives: 1, 2
     [java] As a result, alternative(s) 2 were disabled for that input
     [java] error(10):  internal error: Can't get property indirectDelegates using method get/isIndirectDelegates from org.antlr.tool.Grammar instance : java.lang.NullPointerException
```

**Comment by Stewori** [comment] 2016-11-16 23:45
This looks rather much like you were building with Java 8, which is currently not supported. Jython runs fine on Java 8, but building still requires Java 7.
An inofficial hack to allow building with Java 8 is to run ant twice. This hack might yield (hidden) flaws, although I couldn't observe any so far.

**Comment by darjus** [comment] 2016-11-16 23:54
What @Stewori said. The root cause is that we're using ANTLR3, which is old and does not work on Java8. I'm slowly making progress on migrating to ANTLR4, but that will take a while.

**Comment by Stewori** [comment] 2017-03-06 15:46
As of https://hg.python.org/jython/rev/330556fdad47 Frank changed failonerror setting of org.antlr.Tool target to false:
<java classname="org.antlr.Tool" failonerror="false" fork="true" dir="${jython.base.dir}">
This way the compile process goes through, also on Java 8. It still prints lots of errors, but at least compiling works conveniently again. So closing this one...

**Closed by Stewori** 2017-03-06 15:46 UTC
